# Generated by Django 5.1.5 on 2025-01-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='CustomUser',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
