# Generated by Django 5.1.5 on 2025-01-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0002_alter_customuser_options_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
