# Generated by Django 5.1.5 on 2025-01-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0003_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image/'),
        ),
    ]
